name: ApiRest
on:
  push:
    branches: [main]

workflows_dispatch:

jobs:
  Cypress-Test:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

      - name: Cypress run
        uses: cypress-io/github-action@v6
        continue-on-error: true
        with:
        install-command: npm install
        browser: chrome
        start: npm start

        name: Publish Report
        uses: peaceiris/actions-gh-pages@v3
        with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./mochawesome-report